// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_Menu
global.__objectDepths[1] = 0; // obj_settinggear
global.__objectDepths[2] = 0; // obj_menu_pause
global.__objectDepths[3] = 0; // obj_begin
global.__objectDepths[4] = 0; // obj_quit
global.__objectDepths[5] = 0; // obj_loadquit
global.__objectDepths[6] = 0; // obj_c_a
global.__objectDepths[7] = 0; // obj_c_sr
global.__objectDepths[8] = 0; // obj_c_gje
global.__objectDepths[9] = 0; // obj_expansiontest
global.__objectDepths[10] = 0; // obj_ppa130
global.__objectDepths[11] = 0; // obj_lastsave
global.__objectDepths[12] = 0; // obj_ppa1
global.__objectDepths[13] = 0; // obj_c_incomp
global.__objectDepths[14] = 0; // obj_loadhard
global.__objectDepths[15] = 0; // obj_mattiemonster
global.__objectDepths[16] = 0; // obj_loadtitle
global.__objectDepths[17] = 0; // obj_manager_menu
global.__objectDepths[18] = 0; // obj_note
global.__objectDepths[19] = 0; // obj_tdemo
global.__objectDepths[20] = 0; // obj_ppa120
global.__objectDepths[21] = 0; // obj_returngame
global.__objectDepths[22] = 0; // obj_gamesaved
global.__objectDepths[23] = 0; // obj_hardsave
global.__objectDepths[24] = 0; // obj_settings_settingstitle
global.__objectDepths[25] = 0; // obj_returntomenu
global.__objectDepths[26] = 0; // obj_settings_fullscreenToggle
global.__objectDepths[27] = 0; // obj_settings_fullscreenNote
global.__objectDepths[28] = 0; // obj_settings_fullscreen
global.__objectDepths[29] = 0; // obj_settings_fullscreenToggleOb
global.__objectDepths[30] = 0; // obj_pausetitle
global.__objectDepths[31] = 0; // obj_sleeping
global.__objectDepths[32] = 0; // obj_door
global.__objectDepths[33] = 0; // obj_no
global.__objectDepths[34] = 0; // obj_yes
global.__objectDepths[35] = 0; // obj_continue_end
global.__objectDepths[36] = 0; // obj_continuebutton_id
global.__objectDepths[37] = 0; // obj_cube_text
global.__objectDepths[38] = 0; // obj_door2
global.__objectDepths[39] = 0; // obj_actionWalk
global.__objectDepths[40] = 0; // obj_lookCube
global.__objectDepths[41] = 0; // obj_screen
global.__objectDepths[42] = 0; // obj_back
global.__objectDepths[43] = 0; // obj_walkdoorlvl3
global.__objectDepths[44] = 0; // obj_painting1
global.__objectDepths[45] = 0; // obj_continuelvl3
global.__objectDepths[46] = 0; // obj_sign1
global.__objectDepths[47] = 0; // obj_dooredge
global.__objectDepths[48] = 0; // obj_manager_lvl1
global.__objectDepths[49] = 0; // obj_getup
global.__objectDepths[50] = 0; // obj_backtobed
global.__objectDepths[51] = 0; // obj_walktodoor
global.__objectDepths[52] = 0; // obj_leave
global.__objectDepths[53] = 0; // obj_bar
global.__objectDepths[54] = 0; // obj_comingsoon
global.__objectDepths[55] = 0; // obj_number404
global.__objectDepths[56] = 0; // painting2
global.__objectDepths[57] = 0; // obj_upstairs
global.__objectDepths[58] = 0; // obj_goback
global.__objectDepths[59] = 0; // obj_stairs
global.__objectDepths[60] = 0; // intro_date
global.__objectDepths[61] = 0; // obj_enterh404
global.__objectDepths[62] = 0; // obj_signholder
global.__objectDepths[63] = 0; // obj_playervis
global.__objectDepths[64] = 0; // obj_playertop
global.__objectDepths[65] = 0; // obj_player
global.__objectDepths[66] = 0; // obj_woodfloor
global.__objectDepths[67] = 0; // obj_doorprofile
global.__objectDepths[68] = 0; // obj_thelocalpalace
global.__objectDepths[69] = 0; // thatsit_controller
global.__objectDepths[70] = 0; // obj_van_czta
global.__objectDepths[71] = 0; // global_manager
global.__objectDepths[72] = 0; // obj_concretefloor1
global.__objectDepths[73] = 0; // obj_streetlight
global.__objectDepths[74] = 0; // obj_streetlightoff
global.__objectDepths[75] = 0; // obj_streetlightflicker
global.__objectDepths[76] = 0; // obj_insidetable
global.__objectDepths[77] = 0; // lvl2_controller
global.__objectDepths[78] = 0; // obj_insidepc
global.__objectDepths[79] = 0; // obj_foodbox_overflow
global.__objectDepths[80] = 0; // obj_foodbox_normal
global.__objectDepths[81] = 0; // obj_insidetablepc
global.__objectDepths[82] = 0; // stop_windamb
global.__objectDepths[83] = 0; // obj_insidepc_lvl1egg
global.__objectDepths[84] = 0; // obj_streetwater
global.__objectDepths[85] = 0; // obj_thatsit
global.__objectDepths[86] = 0; // obj_message2
global.__objectDepths[87] = 0; // obj_message3
global.__objectDepths[88] = 0; // obj_floorwood
global.__objectDepths[89] = 0; // obj_light_streetlamp
global.__objectDepths[90] = 0; // obj_line
global.__objectDepths[91] = 0; // obj_dev
global.__objectDepths[92] = 0; // obj_con1
global.__objectDepths[93] = 0; // obj_con2
global.__objectDepths[94] = 0; // obj_gametut
global.__objectDepths[95] = 0; // obj_finish
global.__objectDepths[96] = 0; // obj_message1
global.__objectDepths[97] = 0; // obj_choices


global.__objectNames[0] = "obj_Menu";
global.__objectNames[1] = "obj_settinggear";
global.__objectNames[2] = "obj_menu_pause";
global.__objectNames[3] = "obj_begin";
global.__objectNames[4] = "obj_quit";
global.__objectNames[5] = "obj_loadquit";
global.__objectNames[6] = "obj_c_a";
global.__objectNames[7] = "obj_c_sr";
global.__objectNames[8] = "obj_c_gje";
global.__objectNames[9] = "obj_expansiontest";
global.__objectNames[10] = "obj_ppa130";
global.__objectNames[11] = "obj_lastsave";
global.__objectNames[12] = "obj_ppa1";
global.__objectNames[13] = "obj_c_incomp";
global.__objectNames[14] = "obj_loadhard";
global.__objectNames[15] = "obj_mattiemonster";
global.__objectNames[16] = "obj_loadtitle";
global.__objectNames[17] = "obj_manager_menu";
global.__objectNames[18] = "obj_note";
global.__objectNames[19] = "obj_tdemo";
global.__objectNames[20] = "obj_ppa120";
global.__objectNames[21] = "obj_returngame";
global.__objectNames[22] = "obj_gamesaved";
global.__objectNames[23] = "obj_hardsave";
global.__objectNames[24] = "obj_settings_settingstitle";
global.__objectNames[25] = "obj_returntomenu";
global.__objectNames[26] = "obj_settings_fullscreenToggle";
global.__objectNames[27] = "obj_settings_fullscreenNote";
global.__objectNames[28] = "obj_settings_fullscreen";
global.__objectNames[29] = "obj_settings_fullscreenToggleOb";
global.__objectNames[30] = "obj_pausetitle";
global.__objectNames[31] = "obj_sleeping";
global.__objectNames[32] = "obj_door";
global.__objectNames[33] = "obj_no";
global.__objectNames[34] = "obj_yes";
global.__objectNames[35] = "obj_continue_end";
global.__objectNames[36] = "obj_continuebutton_id";
global.__objectNames[37] = "obj_cube_text";
global.__objectNames[38] = "obj_door2";
global.__objectNames[39] = "obj_actionWalk";
global.__objectNames[40] = "obj_lookCube";
global.__objectNames[41] = "obj_screen";
global.__objectNames[42] = "obj_back";
global.__objectNames[43] = "obj_walkdoorlvl3";
global.__objectNames[44] = "obj_painting1";
global.__objectNames[45] = "obj_continuelvl3";
global.__objectNames[46] = "obj_sign1";
global.__objectNames[47] = "obj_dooredge";
global.__objectNames[48] = "obj_manager_lvl1";
global.__objectNames[49] = "obj_getup";
global.__objectNames[50] = "obj_backtobed";
global.__objectNames[51] = "obj_walktodoor";
global.__objectNames[52] = "obj_leave";
global.__objectNames[53] = "obj_bar";
global.__objectNames[54] = "obj_comingsoon";
global.__objectNames[55] = "obj_number404";
global.__objectNames[56] = "painting2";
global.__objectNames[57] = "obj_upstairs";
global.__objectNames[58] = "obj_goback";
global.__objectNames[59] = "obj_stairs";
global.__objectNames[60] = "intro_date";
global.__objectNames[61] = "obj_enterh404";
global.__objectNames[62] = "obj_signholder";
global.__objectNames[63] = "obj_playervis";
global.__objectNames[64] = "obj_playertop";
global.__objectNames[65] = "obj_player";
global.__objectNames[66] = "obj_woodfloor";
global.__objectNames[67] = "obj_doorprofile";
global.__objectNames[68] = "obj_thelocalpalace";
global.__objectNames[69] = "thatsit_controller";
global.__objectNames[70] = "obj_van_czta";
global.__objectNames[71] = "global_manager";
global.__objectNames[72] = "obj_concretefloor1";
global.__objectNames[73] = "obj_streetlight";
global.__objectNames[74] = "obj_streetlightoff";
global.__objectNames[75] = "obj_streetlightflicker";
global.__objectNames[76] = "obj_insidetable";
global.__objectNames[77] = "lvl2_controller";
global.__objectNames[78] = "obj_insidepc";
global.__objectNames[79] = "obj_foodbox_overflow";
global.__objectNames[80] = "obj_foodbox_normal";
global.__objectNames[81] = "obj_insidetablepc";
global.__objectNames[82] = "stop_windamb";
global.__objectNames[83] = "obj_insidepc_lvl1egg";
global.__objectNames[84] = "obj_streetwater";
global.__objectNames[85] = "obj_thatsit";
global.__objectNames[86] = "obj_message2";
global.__objectNames[87] = "obj_message3";
global.__objectNames[88] = "obj_floorwood";
global.__objectNames[89] = "obj_light_streetlamp";
global.__objectNames[90] = "obj_line";
global.__objectNames[91] = "obj_dev";
global.__objectNames[92] = "obj_con1";
global.__objectNames[93] = "obj_con2";
global.__objectNames[94] = "obj_gametut";
global.__objectNames[95] = "obj_finish";
global.__objectNames[96] = "obj_message1";
global.__objectNames[97] = "obj_choices";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for